import type { SocialIntegration, PlatformConfig, SocialPost, SocialDraft, PublishQueueItem } from "./SocialHubTypes";

// Mock Platform Configurations (will come from DB in production)
export const MOCK_PLATFORM_CONFIGS: PlatformConfig[] = [
  {
    id: "1",
    platform: "linkedin",
    display_name: "LinkedIn",
    icon: "Linkedin",
    color: "#0A66C2",
    supports_oauth: true,
    supports_api_key: false,
    supports_read: true,
    supports_publish: true,
    supports_schedule: true,
    supports_media_types: ["text", "image", "video", "article"],
    oauth_scopes: ["r_liteprofile", "r_emailaddress", "w_member_social"],
    developer_portal_url: "https://developer.linkedin.com/",
    max_post_length: 3000,
    is_active: true,
  },
  {
    id: "2",
    platform: "twitter",
    display_name: "Twitter / X",
    icon: "Twitter",
    color: "#1DA1F2",
    supports_oauth: true,
    supports_api_key: true,
    supports_read: true,
    supports_publish: true,
    supports_schedule: true,
    supports_media_types: ["text", "image", "video", "poll"],
    oauth_scopes: ["tweet.read", "tweet.write", "users.read", "offline.access"],
    developer_portal_url: "https://developer.twitter.com/",
    max_post_length: 280,
    is_active: true,
  },
  {
    id: "3",
    platform: "instagram",
    display_name: "Instagram",
    icon: "Instagram",
    color: "#E4405F",
    supports_oauth: true,
    supports_api_key: false,
    supports_read: true,
    supports_publish: true,
    supports_schedule: true,
    supports_media_types: ["image", "video", "reel", "story"],
    oauth_scopes: ["instagram_basic", "instagram_content_publish"],
    developer_portal_url: "https://developers.facebook.com/",
    max_post_length: 2200,
    is_active: true,
  },
  {
    id: "4",
    platform: "facebook",
    display_name: "Facebook",
    icon: "Facebook",
    color: "#1877F2",
    supports_oauth: true,
    supports_api_key: false,
    supports_read: true,
    supports_publish: true,
    supports_schedule: true,
    supports_media_types: ["text", "image", "video", "link"],
    oauth_scopes: ["pages_read_engagement", "pages_manage_posts"],
    developer_portal_url: "https://developers.facebook.com/",
    max_post_length: 63206,
    is_active: true,
  },
  {
    id: "5",
    platform: "youtube",
    display_name: "YouTube",
    icon: "Youtube",
    color: "#FF0000",
    supports_oauth: true,
    supports_api_key: true,
    supports_read: true,
    supports_publish: true,
    supports_schedule: true,
    supports_media_types: ["video"],
    oauth_scopes: ["https://www.googleapis.com/auth/youtube.upload"],
    developer_portal_url: "https://console.cloud.google.com/",
    max_post_length: 5000,
    is_active: true,
  },
  {
    id: "6",
    platform: "tiktok",
    display_name: "TikTok",
    icon: "Music",
    color: "#000000",
    supports_oauth: true,
    supports_api_key: false,
    supports_read: true,
    supports_publish: true,
    supports_schedule: false,
    supports_media_types: ["video"],
    oauth_scopes: ["user.info.basic", "video.upload"],
    developer_portal_url: "https://developers.tiktok.com/",
    max_post_length: 2200,
    is_active: true,
  },
  {
    id: "7",
    platform: "pinterest",
    display_name: "Pinterest",
    icon: "Image",
    color: "#E60023",
    supports_oauth: true,
    supports_api_key: false,
    supports_read: true,
    supports_publish: true,
    supports_schedule: true,
    supports_media_types: ["image", "video", "link"],
    oauth_scopes: ["boards:read", "pins:read", "pins:write"],
    developer_portal_url: "https://developers.pinterest.com/",
    max_post_length: 500,
    is_active: true,
  },
  {
    id: "8",
    platform: "threads",
    display_name: "Threads",
    icon: "MessageCircle",
    color: "#000000",
    supports_oauth: true,
    supports_api_key: false,
    supports_read: true,
    supports_publish: true,
    supports_schedule: false,
    supports_media_types: ["text", "image"],
    oauth_scopes: ["threads_basic", "threads_content_publish"],
    developer_portal_url: "https://developers.facebook.com/",
    max_post_length: 500,
    is_active: true,
  },
  {
    id: "9",
    platform: "telegram",
    display_name: "Telegram",
    icon: "Send",
    color: "#0088CC",
    supports_oauth: false,
    supports_api_key: true,
    supports_read: true,
    supports_publish: true,
    supports_schedule: false,
    supports_media_types: ["text", "image", "video", "audio"],
    oauth_scopes: null,
    developer_portal_url: "https://core.telegram.org/bots",
    max_post_length: 4096,
    is_active: true,
  },
  {
    id: "10",
    platform: "discord",
    display_name: "Discord",
    icon: "MessageSquare",
    color: "#5865F2",
    supports_oauth: false,
    supports_api_key: true,
    supports_read: false,
    supports_publish: true,
    supports_schedule: false,
    supports_media_types: ["text", "image"],
    oauth_scopes: null,
    developer_portal_url: "https://discord.com/developers",
    max_post_length: 2000,
    is_active: true,
  },
  {
    id: "11",
    platform: "reddit",
    display_name: "Reddit",
    icon: "Chrome",
    color: "#FF4500",
    supports_oauth: true,
    supports_api_key: false,
    supports_read: true,
    supports_publish: true,
    supports_schedule: false,
    supports_media_types: ["text", "image", "link"],
    oauth_scopes: ["identity", "submit", "read"],
    developer_portal_url: "https://www.reddit.com/dev/api",
    max_post_length: 40000,
    is_active: true,
  },
  {
    id: "12",
    platform: "whatsapp",
    display_name: "WhatsApp Business",
    icon: "MessageCircle",
    color: "#25D366",
    supports_oauth: false,
    supports_api_key: true,
    supports_read: true,
    supports_publish: true,
    supports_schedule: false,
    supports_media_types: ["text", "image", "video"],
    oauth_scopes: null,
    developer_portal_url: "https://business.whatsapp.com/",
    max_post_length: 4096,
    is_active: true,
  },
];

// Mock Connected Integrations
export const MOCK_INTEGRATIONS: SocialIntegration[] = [
  {
    id: "int-1",
    user_id: "demo-user",
    platform: "linkedin",
    connection_type: "oauth",
    platform_user_id: "john-doe-123",
    platform_username: "johndoe",
    platform_display_name: "John Doe",
    platform_avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=john",
    platform_metadata: {},
    status: "connected",
    last_sync_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    error_message: null,
    scopes: ["r_liteprofile", "r_emailaddress", "w_member_social"],
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "int-2",
    user_id: "demo-user",
    platform: "twitter",
    connection_type: "oauth",
    platform_user_id: "johndoe_x",
    platform_username: "johndoe_x",
    platform_display_name: "John Doe 🚀",
    platform_avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=twitter",
    platform_metadata: {},
    status: "connected",
    last_sync_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    error_message: null,
    scopes: ["tweet.read", "tweet.write"],
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "int-3",
    user_id: "demo-user",
    platform: "instagram",
    connection_type: "oauth",
    platform_user_id: "johndoe.ig",
    platform_username: "johndoe.ig",
    platform_display_name: "John | Creator",
    platform_avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=insta",
    platform_metadata: {},
    status: "expired",
    last_sync_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    error_message: "Token expired. Please reconnect.",
    scopes: ["instagram_basic"],
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock Fetched Posts
export const MOCK_POSTS: SocialPost[] = [
  {
    id: "post-1",
    user_id: "demo-user",
    integration_id: "int-1",
    platform: "linkedin",
    platform_post_id: "urn:li:share:123456",
    platform_permalink: "https://linkedin.com/posts/johndoe_123456",
    post_type: "article",
    content_text: "Excited to share my journey into AI and machine learning! After months of learning and building projects, I've finally launched my first AI-powered application. 🚀\n\nHere are my key takeaways:\n\n1. Start small, iterate fast\n2. Focus on solving real problems\n3. Community support is invaluable\n\n#AI #MachineLearning #TechJourney",
    content_preview: "Excited to share my journey into AI and machine learning!",
    media_urls: [],
    thumbnails: [],
    likes_count: 1247,
    comments_count: 89,
    shares_count: 234,
    views_count: 45000,
    engagement_rate: 3.5,
    posted_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ["AI", "MachineLearning", "TechJourney"],
    mentions: [],
    platform_metadata: {},
    fetched_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "post-2",
    user_id: "demo-user",
    integration_id: "int-2",
    platform: "twitter",
    platform_post_id: "tweet-789",
    platform_permalink: "https://twitter.com/johndoe_x/status/789",
    post_type: "text",
    content_text: "Just shipped a new feature that reduces API response time by 60%! 🔥\n\nSometimes the best optimizations come from questioning your assumptions.",
    content_preview: "Just shipped a new feature that reduces API response time by 60%!",
    media_urls: [],
    thumbnails: [],
    likes_count: 342,
    comments_count: 28,
    shares_count: 67,
    views_count: 12500,
    engagement_rate: 3.2,
    posted_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    hashtags: [],
    mentions: [],
    platform_metadata: {},
    fetched_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "post-3",
    user_id: "demo-user",
    integration_id: "int-1",
    platform: "linkedin",
    platform_post_id: "urn:li:share:789012",
    platform_permalink: "https://linkedin.com/posts/johndoe_789012",
    post_type: "image",
    content_text: "Behind the scenes at our latest product launch! Amazing team effort. 📸",
    content_preview: "Behind the scenes at our latest product launch!",
    media_urls: ["https://picsum.photos/800/600"],
    thumbnails: ["https://picsum.photos/200/150"],
    likes_count: 567,
    comments_count: 34,
    shares_count: 12,
    views_count: 8900,
    engagement_rate: 2.1,
    posted_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ["TeamWork", "ProductLaunch"],
    mentions: [],
    platform_metadata: {},
    fetched_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock Drafts
export const MOCK_DRAFTS: SocialDraft[] = [
  {
    id: "draft-1",
    user_id: "demo-user",
    title: "Weekly Product Update",
    content_text: "🚀 Weekly Update: We've shipped 3 major features this week!\n\n✅ New dashboard analytics\n✅ Improved search functionality\n✅ Dark mode support\n\nThank you for all the feedback. Keep it coming!",
    media_attachments: [],
    post_type: "text",
    platform_content: {},
    target_platforms: ["linkedin", "twitter"],
    scheduled_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: "Asia/Kolkata",
    status: "pending_approval",
    requires_approval: true,
    approved_at: null,
    approved_by: null,
    rejection_reason: null,
    preview_generated_at: null,
    preview_data: {},
    tags: ["product", "update", "features"],
    notes: null,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "draft-2",
    user_id: "demo-user",
    title: "Tech Tips Thread",
    content_text: "🧵 5 productivity tips for developers:\n\n1/ Use keyboard shortcuts - saves hours weekly\n2/ Automate repetitive tasks\n3/ Take regular breaks (Pomodoro technique)\n4/ Learn your IDE inside out\n5/ Document as you code\n\nWhat's your top productivity tip?",
    media_attachments: [],
    post_type: "text",
    platform_content: {},
    target_platforms: ["twitter"],
    scheduled_at: null,
    timezone: "Asia/Kolkata",
    status: "approved",
    requires_approval: true,
    approved_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    approved_by: "demo-user",
    rejection_reason: null,
    preview_generated_at: new Date().toISOString(),
    preview_data: {},
    tags: ["tips", "productivity", "developers"],
    notes: null,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "draft-3",
    user_id: "demo-user",
    title: null,
    content_text: "Working on something exciting! Can't wait to share more details soon. 👀",
    media_attachments: [],
    post_type: "text",
    platform_content: {},
    target_platforms: ["linkedin", "twitter", "instagram"],
    scheduled_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: "Asia/Kolkata",
    status: "scheduled",
    requires_approval: false,
    approved_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    approved_by: "demo-user",
    rejection_reason: null,
    preview_generated_at: null,
    preview_data: {},
    tags: ["teaser"],
    notes: null,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock Publish Queue
export const MOCK_QUEUE: PublishQueueItem[] = [
  {
    id: "queue-1",
    user_id: "demo-user",
    draft_id: "draft-3",
    integration_id: "int-1",
    platform: "linkedin",
    status: "pending",
    priority: 5,
    scheduled_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    started_at: null,
    completed_at: null,
    retry_count: 0,
    max_retries: 3,
    last_error: null,
    next_retry_at: null,
    published_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "queue-2",
    user_id: "demo-user",
    draft_id: "draft-3",
    integration_id: "int-2",
    platform: "twitter",
    status: "pending",
    priority: 5,
    scheduled_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    started_at: null,
    completed_at: null,
    retry_count: 0,
    max_retries: 3,
    last_error: null,
    next_retry_at: null,
    published_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "queue-3",
    user_id: "demo-user",
    draft_id: "old-draft",
    integration_id: "int-1",
    platform: "linkedin",
    status: "completed",
    priority: 5,
    scheduled_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 5000).toISOString(),
    retry_count: 0,
    max_retries: 3,
    last_error: null,
    next_retry_at: null,
    published_id: "pub-1",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "queue-4",
    user_id: "demo-user",
    draft_id: "old-draft-2",
    integration_id: "int-2",
    platform: "twitter",
    status: "failed",
    priority: 5,
    scheduled_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 3000).toISOString(),
    retry_count: 3,
    max_retries: 3,
    last_error: "Rate limit exceeded. Please try again later.",
    next_retry_at: null,
    published_id: null,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
